<a href="https://colab.research.google.com/github/siham2019/numpy_basics/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# info numpy

In [1]:
import numpy as np

In [2]:
d = np.array([23,34,12],dtype="int32")
d

array([23, 34, 12], dtype=int32)

In [3]:
d.dtype

dtype('int32')

In [4]:
d.itemsize

4

In [5]:
a = np.array([23,34,12],dtype="int16")
a

array([23, 34, 12], dtype=int16)

In [6]:
a.itemsize

2

In [7]:
a.size

3

In [8]:
a.ndim

1

In [9]:
a.shape

(3,)

In [10]:
h = np.array([[3,4,6], [2,4,5]])
h

array([[3, 4, 6],
       [2, 4, 5]])

In [11]:
h.ndim

2

In [12]:
h.size

6

In [13]:
h.itemsize

8

# numpy accessing & modifying

In [14]:
f = np.array([
                [2,3,4,6],
                [7,1,3,3]
                ])
f

array([[2, 3, 4, 6],
       [7, 1, 3, 3]])

In [15]:
f[1,:]

array([7, 1, 3, 3])

In [16]:
f[1,1:4]

array([1, 3, 3])

In [17]:
f[1,1:4:1]

array([1, 3, 3])

In [18]:
f[1,1:-2:1]

array([1])

In [19]:
f[1,1:-1:1]

array([1, 3])

In [20]:
b = np.array([[3,5,4,2],[3,5,4,1]])
b

array([[3, 5, 4, 2],
       [3, 5, 4, 1]])

In [21]:
b[0,0:-2:2]

array([3])

In [22]:
df = np.array([ 
               [ [3,5,4,2],[3,5,4,1] ],[ [1,4,7,4] ,[90,34,23,12]  ]
             
             ])
df

array([[[ 3,  5,  4,  2],
        [ 3,  5,  4,  1]],

       [[ 1,  4,  7,  4],
        [90, 34, 23, 12]]])

In [23]:
df.ndim

3

In [24]:
df[1,0,:]

array([1, 4, 7, 4])

In [25]:
df[1,0,0]=34

In [26]:
df[1,0,:]

array([34,  4,  7,  4])

# numpy init array with functions

In [27]:
o = np.ones((3,5))
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
o1 = np.ones((3,5),dtype="int32")
o1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [29]:
z=np.zeros((2,2),dtype="int32")
z

array([[0, 0],
       [0, 0]], dtype=int32)

In [30]:
i=np.identity(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
r=np.random.rand(4,2)
r

array([[0.74310905, 0.38058309],
       [0.68745775, 0.32637446],
       [0.88230627, 0.21756379],
       [0.47231489, 0.91872477]])

In [32]:
ro=np.random.random_sample(r.shape)
ro

array([[0.6605422 , 0.19622348],
       [0.30087259, 0.08841743],
       [0.01359795, 0.75297192],
       [0.94206089, 0.97126933]])

In [33]:
ri=np.random.randint(3,6,(2,2))
ri

array([[3, 3],
       [3, 3]])

In [34]:
_d=np.array([[1,2,3]])
_d

array([[1, 2, 3]])

In [35]:
re=np.repeat(_d,3,axis=1)
re

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [36]:
f = np.full((2,2),3)
f

array([[3, 3],
       [3, 3]])

In [37]:
f1 = np.full_like(f,6)
f1

array([[6, 6],
       [6, 6]])

# initialize array example

In [38]:
example = np.ones((5,5))
example

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
example[1:4,1:4] = example[1:4,1:4]*np.zeros((3,3))
example

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
example[2,2]=example[2,2]+9
example

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# copy array

In [41]:
ex=example.copy()
ex

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
ex[0,0]=3
ex

array([[3., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
example

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Math




In [44]:
a

array([23, 34, 12], dtype=int16)

In [45]:
d

array([23, 34, 12], dtype=int32)

In [46]:
d+a

array([46, 68, 24], dtype=int32)

In [47]:
d-a

array([0, 0, 0], dtype=int32)

In [48]:
d*a

array([ 529, 1156,  144], dtype=int32)

In [49]:
d

array([23, 34, 12], dtype=int32)

In [50]:
d**2

array([ 529, 1156,  144], dtype=int32)

In [51]:
np.sin(a)

array([-0.8462204 ,  0.5290827 , -0.53657293], dtype=float32)

In [52]:
np.cos(a)

array([-0.53283304, -0.8485703 ,  0.84385395], dtype=float32)

# linear algebra

In [53]:
a*d

array([ 529, 1156,  144], dtype=int32)

In [54]:
a.shape,d.shape

((3,), (3,))

In [55]:
np.matmul(a,d)

1829

In [56]:
np.linalg.det(i)

1.0

# statistics

In [57]:
h

array([[3, 4, 6],
       [2, 4, 5]])

In [58]:
# 0  col
# 1  row

In [59]:
np.max(h,axis=0)

array([3, 4, 6])

In [60]:
np.sum(h,axis=0)

array([ 5,  8, 11])

In [61]:
np.sum(h,axis=1)

array([13, 11])

# reorganising array

In [62]:
h

array([[3, 4, 6],
       [2, 4, 5]])

In [63]:
h.size

6

In [67]:
h.reshape((3,2))

array([[3, 4],
       [6, 2],
       [4, 5]])

In [68]:
h

array([[3, 4, 6],
       [2, 4, 5]])

In [73]:
v=np.vstack([h,h])
v

array([[3, 4, 6],
       [2, 4, 5],
       [3, 4, 6],
       [2, 4, 5]])

In [74]:
hor=np.hstack([h,h])
hor

array([[3, 4, 6, 3, 4, 6],
       [2, 4, 5, 2, 4, 5]])

# read from file

[https://github.com/KeithGalli/NumPy/blob/master/data.txt](https://github.com/KeithGalli/NumPy/blob/master/data.txt)

In [ ]:
bb = np.genfromtxt("https://github.com/siham2019/NumPy/blob/master/data.txt",delimiter=",")
bb

In [78]:
d[d>12]

array([23, 34], dtype=int32)

In [80]:
d > 12

array([ True,  True, False])

In [81]:
~(d > 12)

array([False, False,  True])

# np.asarray

In [83]:
mat = np.matrix(np.ones((4,4)))
mat

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [86]:
mat[2,2]=2

In [87]:
mat

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 2., 1.],
        [1., 1., 1., 1.]])

In [88]:
np.asarray(mat)[2]=0

In [89]:
mat

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.]])

# np.flatten

In [91]:
h

array([[3, 4, 6],
       [2, 4, 5]])

In [94]:
h.flatten('C')

array([3, 4, 6, 2, 4, 5])

In [95]:
h.flatten('F')

array([3, 2, 4, 4, 6, 5])

# np arrange

In [96]:
np.arange(3,9,2)

array([3, 5, 7])