<a href="https://colab.research.google.com/github/siham2019/numpy_basics/blob/main/panda_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# series



1.   **series with list**







In [ ]:
list1 = [2,4,2,7]
list1

[2, 4, 2, 7]

In [ ]:
ser_list1 = pd.Series(list1)
ser_list1

0    2
1    4
2    2
3    7
dtype: int64

In [ ]:
labels = ["a","b","c","e"]
ser_list = pd.Series(data=list1,index=labels)
ser_list

a    2
b    4
c    2
e    7
dtype: int64


2.   **serie with  dictionary**



In [ ]:
d = {"a":23,"b":44,"v":77}
d

{'a': 23, 'b': 44, 'v': 77}

In [ ]:
ser_dict=pd.Series(d)
ser_dict

a    23
b    44
v    77
dtype: int64


3.   **serie with numpy array**



In [ ]:
n = np.array([2,3,5,7])
n

array([2, 3, 5, 7])

In [ ]:
ser_num = pd.Series(n)
ser_num

0    2
1    3
2    5
3    7
dtype: int64

# operations series

In [ ]:
ser_num + ser_list1

0     4
1     7
2     7
3    14
dtype: int64

In [ ]:
ser_num - ser_list1

0    0
1   -1
2    3
3    0
dtype: int64

In [ ]:
ser_num / ser_list1

0    1.00
1    0.75
2    2.50
3    1.00
dtype: float64

In [ ]:
ser_num + ser_list

0   NaN
1   NaN
2   NaN
3   NaN
a   NaN
b   NaN
c   NaN
e   NaN
dtype: float64


* operation with numpy   





In [ ]:
np.exp(ser_list1)

0       7.389056
1      54.598150
2       7.389056
3    1096.633158
dtype: float64

* naming serie 


In [ ]:
nz= pd.Series([4,4,4,2],name="khray")
nz

0    4
1    4
2    4
3    2
Name: khray, dtype: int64

In [ ]:
nz.name

'khray'

# dataframe


1.   **with list**




In [ ]:
a1 = np.arange(3,6)
a1

array([3, 4, 5])

In [ ]:
data1 = pd.DataFrame(a1,["K","H","F"],["A"])
data1

A
K  3
H  4
F  5

In [ ]:
random = np.random.randint(23,40,size=(3,4))
random

array([[26, 36, 39, 30],
       [23, 28, 30, 38],
       [26, 35, 30, 39]])

In [ ]:
data2=pd.DataFrame(random,index=["AUDI","LOLO","VAVA"],columns=["price","vitesse","km","l"])
data2

price  vitesse  km   l
AUDI     26       36  39  30
LOLO     23       28  30  38
VAVA     26       35  30  39



2.   **with dictionary**



In [ ]:
dict1={
    "one":[4,7,3,8],
    "two":[8,5,3,2]
}
dict1

{'one': [4, 7, 3, 8], 'two': [8, 5, 3, 2]}

In [ ]:
data3 = pd.DataFrame(dict1)
data3

one  two
0    4    8
1    7    5
2    3    3
3    8    2

In [ ]:
jk=pd.DataFrame(dict1,index=["G","N","B","H"])
jk

one  two
G    4    8
N    7    5
B    3    3
H    8    2

In [ ]:
dict2={"man":pd.Series(
                    
                         [45,77,80],
                       index=["A","N","C"]
                      ),
       "woman":pd.Series(
                    
                         [44,22,11,21],
                       index=["A","N","C","X"]
                      )
      }
f=pd.DataFrame(dict2)
f

man  woman
A  45.0     44
C  80.0     11
N  77.0     22
X   NaN     21

In [ ]:
e=pd.DataFrame.from_dict(dict2,orient="index")
e

A   N   C     X
man    45  77  80   NaN
woman  44  22  11  21.0

In [ ]:
l=pd.DataFrame.from_dict(dict([('n',[2,3,4,4])]),orient="index")
l

0  1  2  3
n  2  3  4  4

In [ ]:
x=pd.DataFrame.from_dict(dict([('n',[2,3,4,4])]),orient="index",columns=['one','two','three',"four"])
x

one  two  three  four
n    2    3      4     4

In [ ]:
j=pd.DataFrame.from_dict(dict([('A', [1,2,3]), ('B', [4,5,6])]),
                      orient='index', columns=['one','two','three'])
j

one  two  three
A    1    2      3
B    4    5      6

In [ ]:
j.shape

(2, 3)

## editing and retreving from dataframe







1.   **retreving**



In [ ]:
j

one  two  three
A    1    2      3
B    4    5      6

In [ ]:
j["one"]

A    1
B    4
Name: one, dtype: int64

In [ ]:
j[["one","two"]] # columns

one  two
A    1    2
B    4    5

In [ ]:
j.loc[['A', 'B'],["one"]]

one
A    1
B    4

In [ ]:
j

one  two  three
A    1    2      3
B    4    5      6


2.   **editing**



In [ ]:
j["avg"]=(j["one"]+j["two"]+j["three"])/3
j

one  two  three  avg
A    1    2      3  2.0
B    4    5      6  5.0

In [ ]:
dic_add = {"one":2,"two":4,"three":6}
j.append(pd.Series(dic_add,name="Z"))

one  two  three     age
A  1.0  2.0    3.0  mineur
Z  2.0  4.0    6.0     NaN

In [ ]:
j.iloc[1]

one      4.0
two      5.0
three    6.0
avg      5.0
Name: B, dtype: float64

In [ ]:
j

one  two  three  avg
A    1    2      3  2.0
B    4    5      6  5.0

In [ ]:
j.drop("B",axis=0,inplace=True)

In [ ]:
j

one  two  three  avg
A    1    2      3  2.0

In [ ]:
j.drop("avg",axis=1)
j

one  two  three
A    1    2      3

In [ ]:
j['age']=['mineur']
j.set_index("age",inplace=True)

In [ ]:
j

one  two  three
age                    
mineur    1    2      3

In [ ]:
j.reset_index(inplace=True)

In [ ]:
j

age  one  two  three
0  mineur    1    2      3

In [ ]:
j.assign(div=j['one'] / j['two'])


age  one  two  three  div
0  mineur    1    2      3  0.5

In [ ]:
f

man  woman
A  45.0     44
C  80.0     11
N  77.0     22
X   NaN     21

In [ ]:
f["age"]=["adolescent","adult","child","young"]

In [ ]:
f

man  woman         age
A  45.0     44  adolescent
C  80.0     11       adult
N  77.0     22       child
X   NaN     21       young

In [ ]:
f.set_index("age",inplace=True)
f

man  woman
age                    
adolescent  45.0     44
adult       80.0     11
child       77.0     22
young        NaN     21

In [ ]:
f.assign(inverse=1/f['man'])

man  woman   inverse
age                              
adolescent  45.0     44  0.022222
adult       80.0     11  0.012500
child       77.0     22  0.012987
young        NaN     21       NaN

In [ ]:
f

man  woman
age                    
adolescent  45.0     44
adult       80.0     11
child       77.0     22
young        NaN     21

In [ ]:
h1=pd.DataFrame([1,np.nan,5])
h1

0
0  1.0
1  NaN
2  5.0

In [ ]:
h2=pd.DataFrame([1,7,5])
h2

0
0  1
1  7
2  5

In [ ]:
h1.combine_first(h2)


0
0  1.0
1  7.0
2  5.0

##  conditional selection


In [ ]:
f

man  woman
age                    
adolescent  45.0     44
adult       80.0     11
child       77.0     22
young        NaN     21

In [ ]:
f["woman"]>20

age
adolescent     True
adult         False
child          True
young          True
Name: woman, dtype: bool

In [ ]:
f[f["woman"]>20]

man  woman
age                    
adolescent  45.0     44
child       77.0     22
young        NaN     21

In [ ]:
f[f["woman"].le(20)]

man  woman
age               
adult  80.0     11

In [ ]:
f[ (f["woman"]<12) & (f["woman"]>4) ]

man  woman
age               
adult  80.0     11

# import data from any ressource